config/routes.rb
KatieScavenger::Application.routes.draw do
  root to: "clues#index"
  resources :clues, only: [:index, :show]
  match "/answer/:id" => "clues#answer", via: :post, as: :check_answer

  get 'selfish', to: 'clues#selfish'
  get 'lizandnat', to: 'clues#liznat'
end

app/models/clue.rb
class Clue < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clues_controller.rb
class CluesController < ApplicationController
  def index
    @first_clue = Clue.find(1)
  end

  def show
    if params[:id].to_i < 23
      @clue = Clue.find(params[:id])
    end
  end

  def answer
    this_clue = Clue.find(params[:id])
    katies_answer = params[:clue][:answer]
    if this_clue.answer.downcase == katies_answer.downcase
      redirect_to action: "show", id: (params[:id].to_i + 1)
    else
      flash[:error] = "Do better."
      redirect_to action: "show", id: (params[:id].to_i)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/clues/index.html.erb
<div class="clue">
  <%= @first_clue.text %>
</div>

<%= button_to @first_clue.button_text, clue_path(@first_clue.id + 1), method: :get %>

app/views/clues/liznat.html.erb
<div class="haiku">
  IN THAT CASE, <br/>we wrote you a haiku!<br/><br/>
  Always so caring<br/>
  Loving and so lovable<br/>
  Has her nipple pierced.<br/><br/>
</div>
<%= image_tag "liznat.jpg", :alt => "we LOVE you", :class => "liznat" %>
<div class="haiku">See you on the 4th.</div>
<div>love, nat & liz</div>

app/views/clues/selfish.html.erb
<div class="clue">
  Selfish Katie. You think we'd let you have all of the fun without Scottie? Try again on January 4th when you're back in your city.
</div>
<%= button_to "Ok, I'll be the bigger person.", lizandnat_path, method: :get %>

app/views/clues/show.html.erb
<% if @clue %>
  <div class="clue">
    <%= @clue.text %>
  </div>

  <% if @clue.answer %>
    <%= form_for @clue, as: :clue, url: check_answer_path(@clue), method: :post do |f| %>
      <%= f.text_field :answer, value: "" %><br/>
      <% if flash[:error] %>
        <%= f.submit flash[:error] %>
      <% else %>
        <%= f.submit @clue.button_text %>
      <% end %>
    <% end %>
  <% else %>
    <%= button_to @clue.button_text, clue_path(@clue.id + 1), method: :get %>
  <% end %>

<% else %>
  You did it!<br/>Dinner's on us!<br/><br/>
  <%= image_tag "liznat.jpg", :alt => "we LOVE you", :class => "liznat" %><br/>
  merry xmas!<br/>love, nat & liz
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="initial-scale=1.0">
  <title>Katie and Scott's hunt for the pot of gold at the end of the rainbow</title>
  <link href='http://fonts.googleapis.com/css?family=Belgrano' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="overlay"></div>
<div id="container">
  <%= yield %>
</div>

</body>
</html>